[DEBUG]
;Whether to enable logging
;Log level: 1 for fatal, 2 for error, 3 for warning, 4 for info, 5 for trace, 6 for debug (logs all)
loglevel=1
;Whether to save input data: 0 means no, 1 means write to current directory, file name is InputData_*.dav
inputdata=0
;Whether to enable D3D11 flip mode: 0 means disabled, 1 means enabled. Effective only on Windows 10 (and above). Some computers must force enable this to display video.
enabled3d11flip=0
;Configure which channel's logs to print. -1 means disabled
printlogport=-1
;Whether to enable VA-API hardware decoding: 0 means disabled, 1 means enabled. Only effective for Linux hardware decoding
enablevadecode=1
;Whether to enable graphics diagnostic function. Currently only supports real-time streams. The parameter before the comma represents the port number; the parameter after the comma indicates enablement: 0 means disabled, 1 means enabled
enablegraphicsanalyze=0,0
;Image overlay detection curve type: 1 for rendering interval curve, 2 for streaming interval curve, 3 for rendering interface time consumption curve
graphicscurvetype=0